namespace LoyaltySystem.Core.Models;

public static class Constants
{
    public const string Pk                         = "PK";
    public const string Sk                         = "SK";
    public const string UserId                     = "UserId";
    public const string CardId                     = "CardId";
    public const string StampId                    = "StampId";
    public const string StampDate                  = "StampDate";
    public const string Points                     = "Points";
    public const string CampaignId                 = "CampaignId";
    public const string EntityTypeAttName          = "EntityType";
    public const string Email                      = "Email";
    public const string PhoneNumber                = "PhoneNumber";
    public const string FirstName                  = "FirstName";
    public const string LastName                   = "LastName";
    public const string Status                     = "Status";
    public const string DateOfBirth                = "DateOfBirth";
    public const string BusinessId                 = "BusinessId";
    public const string OwnerId                    = "OwnerId";
    public const string Name                       = "Name";
    public const string Description                = "Desc";
    public const string TokenId                    = "TokenId";
    public const string Rewards                    = "Rewards";
    public const string StartTime                  = "StartTime";
    public const string EndTime                    = "EndTime";
    public const string IsActive                   = "IsActive";
    public const string IssueDate                  = "IssueDate";
    public const string LastStampDate              = "LastStampDate";
    public const string OpeningHoursAttName        = "OpeningHours";
    public const string LocationAttributeName      = "Location";
    public const string Role                       = "Role";
    public const string RewardId                   = "RewardId";
    public const string RedeemDate                 = "RedeemDate";
    public const string LastUpdatedDate            = "LastUpdatedDate";
    public const string LastRedeemDate             = "LastRedeemDate";
    public const string Timestamp                  = "Timestamp";
    public const string VerifiedDate               = "VerifiedDate";
    public const string EmailTokenAttName          = "EmailToken";
    public const string ExpiryDate                 = "ExpiryDate";
    public const string CreationDate               = "CreationDate";
    public const string BusinessUserListPk         = "BusinessUserList-PK";
    public const string BusinessUserListSk         = "BusinessUserList-SK";
    public const string BusinessLoyaltyListPk      = "BusinessLoyaltyList-PK";
    public const string BusinessLoyaltyListSk      = "BusinessLoyaltyList-SK";
    public const string WebAddress                 = "http://localhost:3000";
    
    public const string UserPrefix                 = "User#";
    public const string BusinessPrefix             = "Business#";
    public const string CardPrefix                 = "Card#";
    public const string CampaignPrefix             = "Campaign#";
    public const string MetaUserInfo               = "Meta#UserInfo";
    public const string MetaBusinessInfo           = "Meta#BusinessInfo";
    public const string PermissionBusinessPrefix   = "Permission#Business#";
    public const string CardBusinessPrefix         = "Card#Business#";
    public const string CardUserPrefix             = "Card#User#";
    public const string TokenPrefix                = "Token#";
    public const string PermissionUserPrefix       = "Permission#User#";
    public const string ActionStampBusinessPrefix  = "Action#Stamp#Business#";
    public const string ActionRedeemBusinessPrefix = "Action#Redeem#Business#";
}